import type { Metadata } from 'next';
import { Nunito } from 'next/font/google';
import './globals.css';
import { config } from '@fortawesome/fontawesome-svg-core';
import '@fortawesome/fontawesome-svg-core/styles.css';
import QueryProvider from '@/components/providers/QueryProvider';
import { Toaster } from 'react-hot-toast';
import { ReactNode } from 'react';
import NextAuthProvider from '@/components/providers/NextAuthProvider';
import { NextIntlClientProvider } from 'next-intl';

config.autoAddCss = false;
const nunito = Nunito({
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${nunito.className} antialiased`}>
        <NextIntlClientProvider>
          <NextAuthProvider>
            <QueryProvider>{children}</QueryProvider>
          </NextAuthProvider>
        </NextIntlClientProvider>
        <Toaster
          position="top-center"
          toastOptions={{
            duration: 3000,
            style: {
              fontSize: '14px',
              fontWeight: '600',
              borderRadius: '12px',
              padding: '12px 16px',
            },
            success: {
              style: {
                background: 'rgba(10, 20, 50, 0.95)',
                color: 'white',
                border: '1px solid rgba(147, 197, 253, 0.3)',
              },
              iconTheme: {
                primary: 'white',
                secondary: 'rgba(10, 20, 50, 0.95)',
              },
            },
            error: {
              style: {
                background: 'rgba(20, 10, 10, 0.95)',
                color: 'white',
                border: '1px solid rgba(248, 113, 113, 0.3)',
              },
              iconTheme: {
                primary: '#f87171',
                secondary: 'rgba(20, 10, 10, 0.95)',
              },
            },
          }}
        />
      </body>
    </html>
  );
}
